### ISSUE TITLE
When renaming Mysql column, it may use column definition from another table

### ISSUE THREAD

**Issue by Socolin** [fluentmigrator/fluentmigrator#1114]
I have a server with multiple version of a database, for testing, production etc...

I found that rename may change type of a column because it use data from `information_schema.COLUMNS` to build the rename request, but it don't target the current database, and in my case it use column definition from another database and that cause the migration to fail (when renaming it convert a BIGINT to an INT and there is a FK that don't allow this change)

https://github.com/hazzik/fluentmigrator/blob/996b63fddb0eaf8faa09032f5abf5d0459158e7b/src/FluentMigrator.Runner/Generators/MySql/MySqlGenerator.cs#L61

I think this could be fixed by adding ` AND TABLE_SCHEMA= ...`

**Comment by jzabroski** [comment]
@Socolin You're linking to a 7 year old fork of the code... https://github.com/hazzik/fluentmigrator/ is not https://github.com/fluentmigrator/fluentmigrator/

The links are here: https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator.Runner.MySql/Generators/MySql/MySql4Generator.cs#L103

and https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator.Runner.MySql/Generators/MySql/MySql5Generator.cs (effectively, it uses MySql4Generator, but just linking for review).

**Comment by jzabroski** [comment]
@Socolin It appears the issue is this: [`CREATE {DATABASE | SCHEMA}`](https://dev.mysql.com/doc/refman/8.0/en/create-database.html)

MySQL doesn't support schemas in the same way that other databases systems do.   In Oracle schema is synonymous with user (perhaps more accurately, schema is a list of all objects created under a user). MSSQL distinguishes all three (and as a result, when accessing a table from a different database, the name must be qualified by both database and schema, e.g. database1.dbo.table2.

In your case, _based on the linked documentation_, I'm VERY curious what TABLE_SCHEMA says in your database, and how specifying TABLE_SCHEMA fixes any problems for you.

Sorry to hear about your database woes.  What a crap problem to deal with on the weekend.

**Comment by jzabroski** [comment]
@fubar-coder Any chance you can confirm my analysis?

**Comment by Socolin** [comment]
Sorry for the link to another repository, I failed my copy/paste here the code in this one

https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.MySql/Processors/MySql/MySqlProcessor.cs#L210

I'm using fluent migrator with `AddMySql5` and I'm using MySQL 8.0.17

I've found a workaround by creating a user/database so it isolate

> In your case, based on the linked documentation, I'm VERY curious what TABLE_SCHEMA says in your database, and how specifying TABLE_SCHEMA fixes any problems for you.

```
mysql> SELECT * FROM information_schema.COLUMNS                  WHERE TABLE_NAME = 'character_modifiers' AND COLUMN_NAME = 'characterId' \G;
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: naheulbook
              TABLE_NAME: character_modifiers
             COLUMN_NAME: characterId
        ORDINAL_POSITION: 3
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: bigint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 19
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: bigint(20)
              COLUMN_KEY: MUL
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 2. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: naheulbook_integration
              TABLE_NAME: character_modifiers
             COLUMN_NAME: characterId
        ORDINAL_POSITION: 17
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: int
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 10
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: int(11)
              COLUMN_KEY: MUL
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 3. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: naheulbook_test
              TABLE_NAME: character_modifiers
             COLUMN_NAME: characterId
        ORDINAL_POSITION: 3
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: bigint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 19
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: bigint(20)
              COLUMN_KEY: MUL
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
3 rows in set (0.00 sec)
```

`TABLE_SCHEMA` contains the name of the database I created with `CREATE DATABASE ...`
