### ISSUE TITLE
Two NuGet packages don't get prerelease tag

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#1146]
When NuGet packages are build using Azure Pipelines, the two packages generated by the NuGetCommand task don't get the prerelease tag provided by GitVersion.

```
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)/publish/FluentMigrator.Console.nuspec'
    versioningScheme: 'byBuildNumber'
    buildProperties: '-OutputDirectory "$(Build.ArtifactStagingDirectory)/output" -Properties Configuration=$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)/publish/FluentMigrator.Tools.nuspec'
    versioningScheme: 'byBuildNumber'
    buildProperties: '-OutputDirectory "$(Build.ArtifactStagingDirectory)/output" -Properties Configuration=$(buildConfiguration)'
```

`versioningScheme: 'byBuildNumber'` obviously ignores the **-alpha.XXX** part of the build number.
We need to tweak this somehow until all NuGet packages are versioned identically within the same build, regardless of the type of task is used to build them.

Ref to comment where the issue is discovered: https://github.com/fluentmigrator/fluentmigrator/issues/1142#issuecomment-572823857
